### ISSUE TITLE
Cursor on website behaves funny

### ISSUE THREAD

**Issue by tammojan** [NLeSC/fair-software-frontend#12]
Not sure what causes this, but there's a bug on your website that causes my pointer to behave funny. I'm macos 10.14.6 (18G1012), Fireforx 70.0.1 (64-bit). I have not tested other browsers.

See http://tammo80.nl/files/screenshot.mov

**Comment by jspaaks** [comment]
wowzers. that is not like it should be. thanks for the report!

**Comment by Tommos0** [comment]
Is the situation better here: https://deploy-preview-17--lucid-torvalds-9265e8.netlify.com/ ?

**Comment by tammojan** [comment]
Yes, that solves the issue for me.
