### ISSUE TITLE
setup robots.txt

### ISSUE THREAD

**Issue by Tommos0** [NLeSC/fair-software-frontend#14]
https://github.com/NLeSC/fair-software-frontend/blob/d93175a020daf9bba9bbae7e70937f332fbbf1ea/static/robots.txt

Current robots.txt disables all crawling by search engines. If we want the site to be indexable by google & co it needs to be set up.

**Comment by jmaassen** [comment]
Yes, it would be good if google can find it!

**Comment by Tommos0** [comment]
https://github.com/NLeSC/fair-software-frontend/commit/2fe0e680502aacb2812b40634c962ad4ae969adf
