### ISSUE TITLE
Navigation arrows on left and right side are not visible in Safari on macos

### ISSUE THREAD

**Issue by evertrol** [NLeSC/fair-software-frontend#30]
In Safari on Macos, the navigation arrows (triangles) near the upper left and upper right are not visible (their containing/background boxes are). See attached screenshot.
Hovering over the boxes also doesn't make them appear: the box simply changes its colour from green to black.

<img width="1440" alt="fair-software-missing-arrows-safari" src="https://user-images.githubusercontent.com/735460/74140041-a6c12280-4bf4-11ea-915b-78420e160865.png">

**Comment by mkuzak** [comment]
Also on mac on Safari. What I see is that there is no hand visible in the green rectangle, so when you hover over, it turns black and just disappears.

**Comment by ctwhome** [comment]
Fixed :)
