### ISSUE TITLE
rendering issue on Internet Explorer

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/fair-software-frontend#44]
The endorsement page does not render well in Internet Explorer. Specifically, the logos are scaled in a bad way and it's not possible to scroll to the bottom. See attached screenshot. This is a big deal because a lot of UMCs still use Internet Explorer and employees have no option to install any other web browser.
![thumbnail_image001](https://user-images.githubusercontent.com/208443/85131979-31b3c880-b238-11ea-8c0d-35121702c366.png)

**Comment by ctwhome** [comment]
It would be interesting to see what version of IE they have access to. Is it installed google analytics on the page?
It looks like a CSS incompatibility with ie `object-fit: contain; https://caniuse.com/#feat=object-fit `, we could come with a hack for it.

I don't know about the scroll, but I could test it on a virtual machine if you want me to

**Comment by mkuzak** [comment]
@ctwhome thank you for looking into it. I asked about it, but the person who reported it is on holiday now. We should receive a response sometime next week. I tried to reproduce it with windows 10 and latest version of IE but all worked fine for me.

**Comment by ctwhome** [comment]
I see in windows 10 (ie 11) that the `Endorse page` is the one that is not stretching the images correctly and the scroll doesn't work. The rest of the pages seem to be fine. I'll try to give it a spin

**Comment by mkuzak** [comment]
thank you @ctwhome

**Comment by ctwhome** [comment]
See pull request https://github.com/NLeSC/fair-software-frontend/pull/45
