### ISSUE TITLE
Wording around Codemeta

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/fair-software-frontend#51]
#4 states: "The CodeMeta standard ..."

However, @mkuzak pointed out CodeMeta is not a standard. Is it more correct to say "The CodeMeta specification..." ?

**Comment by mkuzak** [comment]
It's a metadata schema

**Comment by jspaaks** [comment]
Visitors do not care what a bunch of CS peeps call it, they are focused on how it can help them

**Comment by mkuzak** [comment]
It is still factually incorrect. We can find a better term for it but we should not provide incorrect information.

**Comment by c-martinez** [comment]
So we need to word it in a way which is correct, and still understandable for visitors (which I think it what @jspaaks is hinting at?). If we rephrase the first sentence from:

> The CodeMeta standard and the Citation File Format were specifically designed to enable citation of software 

To

> CodeMeta and the Citation File Format were specifically designed to enable citation of software

It would be:
a) understandable for the visitor who doesn't care if it is a standard or a metadata schema
b) factually correct

Does that sound like a good solution?

**Comment by mkuzak** [comment]
works for me

**Comment by jspaaks** [comment]
Good with me, thanks for the suggestion

**Comment by c-martinez** [comment]
Fixed in #52
