### ISSUE TITLE
Recommendation text does not appear on click

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/fair-software-frontend#56]
If I go to https://fair-software.eu/recommendations/license and to click the `#2 Add a license` heading nothing happens. I expected to see the recommendation text like the why and help me choose sections.
To get to see the recommendation text  I have to click well below the heading (where the cursor is not a pointer).

PS. In console I see `ReferenceError: Expo is not define` errors.

**Comment by sverhoeven** [comment]
Poke @ctwhome

**Comment by ctwhome** [comment]
thanks, I updated the GSAP version to remove the vulnerabilities manually https://github.com/NLeSC/fair-software-frontend/pull/60

**Comment by sverhoeven** [comment]
Great, functionailty has been restored.
